### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by lschierer** [nanostores/lit#13]
The NPM for this is out of date, as a result I cannot upgrade nanostores from 0.9.5 to 0.10.2 nor @nanostores/persistent from 0.9.1 to 0.10.1.   Please release an updated NPM that is compatible with the current base nanostores.

**Comment by emilbonnek** [comment]
Version 2.1.1 of `@nanostores/lit` released last month supports `nanostores` 0.10.x.
Is there a problem when using them together, or what is the issue?

**Comment by lschierer** [comment]
```
lschiere@80a997121f31:~/src/schierer/EvonyTKRTips$ grep nanos package.json
    "@nanostores/lit": "^0.2.1",
    "@nanostores/logger": "^0.2.4",
    "@nanostores/persistent": "^0.10.1",
    "nanostores": "^0.10.2",
lschiere@80a997121f31:~/src/schierer/EvonyTKRTips$
```

**Comment by emilbonnek** [comment]
Kindly open an issue on the `@nanostores/logger`  repo👍

**Comment by lschierer** [comment]
[done](https://github.com/nanostores/logger/issues/20)
