### ISSUE TITLE
Add to `awesome-lit`?

### ISSUE THREAD

**Issue by JulianCataldo** [nanostores/lit#4]
This library is so good, it deserves a place here:

https://github.com/web-padawan/awesome-lit

What do you think?

**Comment by emilbonnek** [comment]
That would be nice.
Would you like to make a PR for it there?
I think it could fit under the **extensions** section, and they have contrib guidelines [here](https://github.com/web-padawan/awesome-lit/blob/main/CONTRIBUTING.md)

**Comment by JulianCataldo** [comment]
☑️
https://github.com/web-padawan/awesome-lit/pull/68

Cheers
