### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by leonfbraun** [nanostores/lit#9]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nanostores/lit@0.1.5
npm ERR! Found: lit@3.0.0
npm ERR! node_modules/lit
npm ERR!   lit@"^3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer lit@"^2.6.0" from @nanostores/lit@0.1.5
npm ERR! node_modules/@nanostores/lit
npm ERR!   @nanostores/lit@"^0.1.5" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: lit@2.8.0
npm ERR! node_modules/lit
npm ERR!   peer lit@"^2.6.0" from @nanostores/lit@0.1.5
npm ERR!   node_modules/@nanostores/lit
npm ERR!     @nanostores/lit@"^0.1.5" from the root project

The Package needs to be updated to use the latest lit version.
As a workaround you can use the -f option with your npm install to force the installation.

@emilbonnek

**Comment by emilbonnek** [comment]
Thanks for reporting! I released a new version with the updated peer dependency.
